{
 "title": "Overview",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Connected validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, sum by (kubernetes_pod_name)(aptos_connections{network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})) + 1"
    }
   ]
  },
  {
   "title": "Total staked coins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_total_voting_power{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\"}) / 100000000"
    }
   ]
  },
  {
   "title": "Total supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with supply_per_epoch as (\nselect epoch, FLOOR(supply/1e8) total_supply, sum(voting_power/1e8) total_staking\nfrom (\n  select transaction_epoch, supply\n  from `indexer_mainnet_gcp.coin_supply` \n  QUALIFY ROW_NUMBER() OVER (PARTITION BY transaction_epoch ORDER BY transaction_version DESC) = 1\n) a\njoin `indexer_mainnet_gcp.epoch_validators` b\non a.transaction_epoch = b.epoch\ngroup by 1,2 order by 1),\n\nmax_epoch as (select max(epoch) as epoch from supply_per_epoch)\n\nselect total_supply from supply_per_epoch a join max_epoch b on a.epoch = b.epoch\n"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(aptos_consensus_last_committed_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Avg Gas Per Txn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(aptos_vm_txn_gas_usage_sum{kubernetes_pod_name=~\".*\", role=~\"validator\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1h]) / rate(aptos_vm_txn_gas_usage_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*\", role=~\"validator\"}[1h])"
    }
   ]
  },
  {
   "title": "Total User transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "select count(1) cnt\nfrom `indexer_mainnet_gcp.user_transactions`"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_epoch{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Transaction type distribution (since beginning)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 1, "y": 5 },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "select entry_function_id_str, count(1) from `indexer_mainnet_gcp.user_transactions` group by 1 order by 2 desc LIMIT 10"
    }
   ]
  },
  {
   "title": "Daily active users (unique senders)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 13, "y": 5 },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "select substr(cast(timestamp as string),1,10) ds, count(distinct sender) cnt\nfrom `indexer_mainnet_gcp.user_transactions`\ngroup by 1 order by 1 desc limit 10"
    }
   ]
  },
  {
   "title": "Blockchain health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync lagging validator",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(clamp_min(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", data_type=\"transactions\"} - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", type=\"synced\"}, 0) > 50000) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Sync lagging validators",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 3, "y": 10 },
     "targets": [
      {
       "expr": "sort_desc(clamp_min(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", data_type=\"transactions\"} - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",  role=~\"validator\", type=\"synced\"}, 0) > 50000 )"
      }
     ]
    },
    {
     "title": "Participating Stake ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.5, aptos_chain_health_participating_voting_power_last_100_rounds{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"}/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"})*100"
      }
     ]
    },
    {
     "title": "Participating Validators ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.5, aptos_chain_health_participating_num_validators_last_100_rounds{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"}/aptos_chain_health_total_num_validators{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"})*100"
      }
     ]
    },
    {
     "title": "Connected but not Participating in Consensus",
     "type": "table",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
     "targets": [
      {
       "expr": "aptos_committed_votes_in_window{chain_name=~\"premainnet\", namespace=~\"telemetry-service\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\"} + aptos_committed_proposals_in_window{chain_name=~\"premainnet\", namespace=~\"telemetry-service\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\"} == 0"
      }
     ]
    }
   ]
  },
  {
   "title": "SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Committed blocks per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "blocks per sec" }
     ],
     "targets": [
      {
       "expr": "quantile(0.67, rate(aptos_consensus_last_committed_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role=\"validator\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Committed user transactions per sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "quantile(0.67, rate(aptos_consensus_last_committed_version{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"}[1m]) - 2 * rate(aptos_consensus_last_committed_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Validators participating in consensus (~20m stale)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quantile(0.67, aptos_chain_health_participating_voting_power_last_100_rounds{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"} * 100/aptos_chain_health_total_voting_power{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"})",
       "legendFormat": "participating stake"
      },
      {
       "expr": "quantile(0.67, aptos_chain_health_participating_num_validators_last_100_rounds{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"} * 100/aptos_chain_health_total_num_validators{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"validator\"})",
       "legendFormat": "participating validators"
      }
     ]
    }
   ]
  },
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Validator Connected Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(aptos_connections{network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Synced Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{type=\"synced\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-synced"
    }
   ]
  },
  {
   "title": "Validators lagging behind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", data_type=\"transactions\"}  - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"telemetry-service\",kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", type=\"synced\"} > 30000)  OR on() vector(0) ",
     "legendFormat": "{{kubernetes_pod_name}}-committed"
    }
   ]
  },
  {
   "title": "Fullnode health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fullnode Connected Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, network_id)(aptos_connections{role_type=\"full_node\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Fullnode Upstream Peers",
   "type": "graph",
   "description": "Number of upstream validator peers a full node can proxy transactions up to",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_mempool_active_upstream_peers_count{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator_fullnode\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fullnodes lagging behind",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",  role=\"validator_fullnode\", data_type=\"transactions\"}  - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"telemetry-service\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator_fullnode\", type=\"synced\"} > 50000)  OR on() vector(0)",
     "legendFormat": "{{kubernetes_pod_name}}-committed"
    }
   ]
  },
  {
   "title": "Synced Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{type=\"synced\", role=\"fullnode\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-synced"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Proposal failure count (in window)",
     "type": "timeseries",
     "description": "Proposal failure rate in leader election window. Value goes back to 0 once node is not asked to propose at all in the window",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "aptos_failed_proposals_in_window{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\"} ",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Participating in consensus",
     "type": "timeseries",
     "description": "Participating in consensus in leader election window (either voted in last num_validators rounds, or proposed in last 10*num_validators rounds)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "clamp_max(aptos_committed_votes_in_window{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\"} + aptos_committed_proposals_in_window{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\"}, 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "description": "The error rate of main loop.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_consensus_error_count{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m]) / on (kubernetes_pod_name) rate(consensus_duration_count{op='main_loop', kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Round Timeout Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(aptos_consensus_timeout_rounds_count{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Current Round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "aptos_consensus_current_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{index=\"system_ttl\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "e2e latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.5, rate(aptos_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", scope=\"e2e\"}[1m])/rate(aptos_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", scope=\"e2e\"}[1m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, rate(aptos_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", scope=\"e2e\"}[1m])/rate(aptos_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", scope=\"e2e\"}[1m]))",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.99, rate(aptos_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", scope=\"e2e\"}[1m])/rate(aptos_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", scope=\"e2e\"}[1m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Block execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_execute_block_seconds_bucket{role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aptos_executor_execute_block_seconds_bucket{role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_execute_block_seconds_bucket{role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "State Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator Syncing throughput ",
     "type": "timeseries",
     "description": "The storage synchronizer throughput (versions per second).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\",type=\"synced\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{type}}"
      }
     ]
    },
    {
     "title": "Validator Sync lag (behind highest known)",
     "type": "timeseries",
     "description": "The difference between the highest advertised version and the currently synced version.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "clamp_min(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", data_type=\"transactions\"} - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"validator\", type=\"synced\"}, 0)",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator CPU Usage (Linux Only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "(1-($Idle/($Total-$Guest)))*10", "type": "math" }
     ]
    },
    {
     "title": "Validator Memory RSS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "node_process_memory{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Validator Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_disk_total_space{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} - node_disk_available_space{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validator IO Operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_linux_disk_num_reads{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval]) + rate(node_linux_disk_num_writes{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
       "legendFormat": "{{kubernetes_pod_name}} {{name}}"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_total_received{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval]) + rate(node_network_total_transmitted{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validator CPU time waiting for IO",
     "type": "timeseries",
     "description": "100% = 1vCPU",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_linux_system_cpu_usage{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=~\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"iowait_ms\"}[1m]) / 1000",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU Architecture and Build", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU brand & core count (COUNT distribution)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \npre_result as (\n  select \n    distinct peer_id \n    ,first_value(last_cpu_vendor_id) over (partition by peer_id order by epoch desc) as cpu_brand\n    ,first_value(rewards_growth) over (partition by peer_id order by epoch desc) as rewards_growth\n    ,first_value(last_cpu_core_count) over (partition by peer_id order by epoch desc) as cpu_core_count\n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics`\n  where \n    chain_name = '$chain_name'\n    -- and substring($kubernetes_pod_name, length($kubernetes_pod_name)-64)\n)\n\n,pre_result2 as (\n  select\n    substring(concat('00',cast(cpu_core_count as string)),-3) as cpu_core_count \n    ,cpu_brand\n    ,avg(rewards_growth) as rewards_growth\n    ,count(distinct peer_id) as count_peers\n  from pre_result\n  group by 1,2\n  order by 2\n)\n\nselect \n  coalesce(t1.cpu_core_count,t2.cpu_core_count) as cpu_core_count\n  -- cast(concat('2000-01-01 00:00:00.',cast(coalesce(t1.cpu_core_count,t2.cpu_core_count) as string)) as timestamp) as cpu_core_count\n  ,t1.count_peers as AuthenticAMD\n  ,t2.count_peers as GenuineIntel\nfrom (\n  select cpu_core_count, rewards_growth, count_peers\n  from pre_result2\n  where cpu_brand = 'AuthenticAMD') t1\nfull join (\n  select cpu_core_count, rewards_growth, count_peers\n  from pre_result2\n  where cpu_brand = 'GenuineIntel') t2\non t1.cpu_core_count = t2.cpu_core_count\norder by cpu_core_count"
    }
   ]
  },
  {
   "title": "LATEST EPOCH voting power distribution",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 53 },
   "targets": [
    {
     "dataset": "aptos_node_telemetry",
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \n result as (\n  select \n    distinct peer_id\n    ,first_value(latitude) over (partition by peer_id order by epoch desc) as latitude\n    ,first_value(longitude) over (partition by peer_id order by epoch desc) as longitude\n    ,first_value(voting_power) over (partition by peer_id order by epoch desc) as voting_power\n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics`\n  where \n    chain_name = '$chain_name')\n  \n  select *, \n    voting_power/(sum(voting_power) over ()) as pct_total_voting_power\n  from result\n  order by pct_total_voting_power desc"
    }
   ]
  },
  {
   "title": "LATEST EPOCH rewards growth",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 61 },
   "targets": [
    {
     "dataset": "aptos_node_telemetry",
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \n result as (\n  select \n    distinct peer_id\n    ,first_value(latitude) over (partition by peer_id order by epoch desc) as latitude\n    ,first_value(longitude) over (partition by peer_id order by epoch desc) as longitude\n    ,first_value(voting_power) over (partition by peer_id order by epoch desc) as voting_power\n    ,first_value(rewards_growth) over (partition by peer_id order by epoch desc) as latest_epoch_rewards_growth\n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics`\n  where \n    chain_name = '$chain_name')\n  \n  select * from result"
    }
   ]
  },
  {
   "title": "Latest Build Distribution",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 64 },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \nresult0 as (\n  select \n    distinct t1.peer_id, \n    first_value(t1.latest_hash) over (partition by t1.peer_id order by t1.epoch desc) as latest_hash, \n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics` t1\n  where \n    chain_name = '$chain_name'\n    -- and substring($kubernetes_pod_name, length($kubernetes_pod_name)-64)\n)\n\nselect \n  t1.latest_hash, \n  t2.build_time, \n  count(distinct t1.peer_id) as num_validators\nfrom result0 t1\nleft join `analytics-test-345723.aptos_node_telemetry.build_versions` t2\n  on t1.latest_hash = t2.build_commit_hash\ngroup by 1,2\n"
    }
   ]
  },
  {
   "title": "System Name",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \nresult0 as (\n  select \n    distinct t1.peer_id, \n    first_value(t1.last_system_name) over (partition by t1.peer_id order by t1.epoch desc) as system_name, \n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics` t1\n  where \n    chain_name = '$chain_name'\n    -- and substring($kubernetes_pod_name, length($kubernetes_pod_name)-64)\n)\n\nselect \n  t1.system_name, \n  count(distinct t1.peer_id) as num_validators\nfrom result0 t1\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "LATEST EPOCH rewards growth (ONLY when < 99.9)",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 69 },
   "targets": [
    {
     "dataset": "aptos_node_telemetry",
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \n result as (\n  select \n    distinct peer_id\n    ,first_value(latitude) over (partition by peer_id order by epoch desc) as latitude\n    ,first_value(longitude) over (partition by peer_id order by epoch desc) as longitude\n    ,first_value(voting_power) over (partition by peer_id order by epoch desc) as voting_power\n    ,first_value(rewards_growth) over (partition by peer_id order by epoch desc) as latest_epoch_rewards_growth\n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics`\n  where \n    chain_name = '$chain_name')\n  \n  select * from result\n  where latest_epoch_rewards_growth < 99.9"
    }
   ]
  },
  {
   "title": "Disk Type",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "with \nresult0 as (\n  select \n    distinct t1.peer_id, \n    first_value(t1.last_disk_type) over (partition by t1.peer_id order by t1.epoch desc) as disk_type, \n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics` t1\n  where \n    chain_name = '$chain_name'\n    -- and substring($kubernetes_pod_name, length($kubernetes_pod_name)-64)\n)\n\nselect \n  t1.disk_type, \n  count(distinct t1.peer_id) as num_validators\nfrom result0 t1\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "AVERAGE rewards growth (ONLY when < 99.9)",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 76 },
   "targets": [
    {
     "dataset": "aptos_node_telemetry",
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": " with \n result as (\n  select \n    distinct peer_id\n    ,first_value(latitude) over (partition by peer_id order by epoch desc) as latitude\n    ,first_value(longitude) over (partition by peer_id order by epoch desc) as longitude\n    ,first_value(voting_power) over (partition by peer_id order by epoch desc) as voting_power\n    ,avg(rewards_growth) over (partition by peer_id) as rewards_growth\n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics`\n  where \n    chain_name = '$chain_name')\n  \n  select * from result\n  where rewards_growth < 99.9"
    }
   ]
  },
  {
   "title": "Latest CPU Architecture & Build Info",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 81 },
   "targets": [
    {
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "  select \n    distinct peer_id, \n    first_value(latest_hash) over (partition by peer_id order by epoch desc) as latest_hash,\n    first_value(latest_build_latency_hours) over (partition by peer_id order by epoch desc) as latest_build_latency_hours,\n    first_value(last_cpu_brand) over (partition by peer_id order by epoch desc) as cpu_brand,\n    first_value(last_cpu_count) over (partition by peer_id order by epoch desc) as cpu_count,\n    first_value(last_cpu_core_count) over (partition by peer_id order by epoch desc) as cpu_core_count,\n    first_value(last_cpu_frequency) over (partition by peer_id order by epoch desc) as cpu_frequency,\n    first_value(last_cpu_vendor_id) over (partition by peer_id order by epoch desc) as cpu_vendor_id,\n    first_value(last_disk_type) over (partition by peer_id order by epoch desc) as disk_type,\n    first_value(sum_disk_available_space/sum_disk_total_space) \n      over (partition by peer_id order by epoch desc) as avg_disk_pct_available,\n    first_value(sum_memory_available/sum_disk_total_space) \n      over (partition by peer_id order by epoch desc) as avg_mem_pct_available,\n    first_value(sum_disk_total_space) over (partition by peer_id order by epoch desc) as sum_disk_total_space,\n    first_value(sum_memory_total) over (partition by peer_id order by epoch desc) as sum_memory_total,\n    first_value(last_system_name) over (partition by peer_id order by epoch desc) as system_name,\n    -- substring($kubernetes_pod_name, len($kubernetes_pod_name)-64)\n  from `analytics-test-345723.aptos_node_telemetry.all_chain_telemetry_rollup_metrics`\n  where \n    chain_name = '$chain_name'\n    -- and substring($kubernetes_pod_name, length($kubernetes_pod_name)-64)"
    }
   ]
  }
 ]
}